export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <div>
      <h1>the content in about</h1>
      {children}
    </div>
  )
}
