"use client";
// import { Poppins } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import 'bootstrap-icons/font/bootstrap-icons.css'
import { useEffect, useState } from "react";
import { useRouter } from 'next/navigation';

import Link from "next/link";

// const poppins = Poppins({
//   weight: ["400", "700"],
//   subsets: ["latin"],
// });

const metadata = {
  title: "home",
  description: "Generated by Next.js",
  keywords: "web development, npm, html, css, nextjs, reactjs",
};



export default function RootLayout({ children }) {
  useEffect(() => {
    import("bootstrap/dist/js/bootstrap");
  }, []);

  const router = useRouter();
  const router1 = useRouter();
  const [result, setResult] = useState(null);

  useEffect(() => {
    const fetchProfileData = async () => {
      const requestOptions = {
        method: 'GET',
        credentials: 'include',
        redirect: 'follow',
      };

      try {
        const response = await fetch('http://127.0.0.1:8000/api/profile', requestOptions);
        if (response.status === 200) {
          const result = await response.json();
          setResult(result);
          // window.location.href = "/";
        } else {
          console.log('error', response.status);
        }
      } catch (error) {
        if (error.response && error.response.status === 401) {
          router.push('/signin');
        } else {
          console.log('error', error);
        }
      }
    };

    fetchProfileData();
  }, [router]);


  function handleLogout() {

    fetch('http://127.0.0.1:8000/api/logout', {
      method: 'POST',
      credentials: 'include' // This is important if you're using cookies
    })
      .then(response => {
        if (response.status === 404) {
          setResult(null);
          router1.push('/login'); // Redirect to /signin using router
        } else {
          // Handle successful response
        }
      })
      .catch(error => {
        // Handle error
      });
  }
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{metadata.title}</title>
      </head>
      <body >

        <div>
          <nav className="navbar navbar-expand-lg bg-light">
            <div className="container-fluid">
              <Link className="navbar-brand" aria-current="page" href="/">
                Event
              </Link>
              <button
                className="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span className="navbar-toggler-icon"></span>
              </button>
              <div
                className="collapse navbar-collapse"
                id="navbarSupportedContent"
              >
                <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                  <li className="nav-item">
                    <Link className="nav-link active" aria-current="page" href="/">
                      Home
                    </Link>
                  </li>
                  <li className="nav-item dropdown">
                    <a
                      className="nav-link dropdown-toggle"
                      href="#"
                      role="button"
                      data-bs-toggle="dropdown"
                      aria-expanded="false"
                    >
                      About
                    </a>
                    <ul className="dropdown-menu">
                      <li>
                        <Link href="/about" className="dropdown-item">
                          About
                        </Link>
                      </li>
                      <li>
                        <Link href="/about/team" className="dropdown-item">
                          About Team
                        </Link>
                      </li>
                    </ul>
                  </li>

                  {result ? (
                    <>
                     <li className="nav-item dropdown">
                     <a
                       className="nav-link dropdown-toggle"
                       href="#"
                       role="button"
                       data-bs-toggle="dropdown"
                       aria-expanded="false"
                     >
                       Event
                     </a>
                     <ul className="dropdown-menu">
                       <li>
                         <Link href="/evenenment" className="dropdown-item">
                           My Events
                         </Link>
                       </li>
                       <li>
                         <Link href="/evenenment/add" className="dropdown-item">
                           Add Event
                         </Link>
                       </li>
                     </ul>
                   </li>
                   <li className="nav-item">
                     <Link href="/reservation" className="nav-link">
                       Reservation
                     </Link>
                   </li>
                   </>
                  ):(<></>)}
                 
                  <li className="nav-item">
                    <Link href="/contact" className="nav-link">
                      Contact
                    </Link>
                  </li>


                </ul>
                <div className="d-flex">
                  {result ? (
                    <ul className="navbar-nav me-auto mb-0 mb-lg-0">
                      <li className="nav-item">
                        <Link href="/profile" className="nav-link">
                          <div className="rounded-circle fs-3">
                            <span>
                              <i className="bi bi-person-circle"></i>
                            </span>
                          </div>
                        </Link>
                      </li>

                      <li className="nav-item me-5">
                        <div className="nav-item dropdown">
                          <div
                            className="nav-link dropdown-toggle rounded-circle fs-5"
                            role="button"
                            data-bs-toggle="dropdown"
                            aria-expanded="false"
                          >
                            {result.fullName}
                          </div>
                          <ul className="dropdown-menu">
                            <li>
                              <Link href="/profile" className="dropdown-item">
                                profile
                              </Link>
                            </li>
                            <li>
                              <button className="dropdown-item" onClick={handleLogout}>Logout</button>
                            </li>
                          </ul>
                        </div>
                      </li>
                    </ul>



                  ) : (
                    <ul className="navbar-nav me-auto mb-2 mb-lg-0">

                      <li className="nav-item">
                        <Link href="/login" className="nav-link">
                          Sign In
                        </Link>
                      </li>

                      <li className="nav-item me-5">
                        <Link href="/register" className="nav-link btn btn-info">
                          Sign Up
                        </Link>
                      </li>

                    </ul>
                  )}



                </div>
              </div>
            </div>
          </nav>
        </div>
        <div className=" container">
          {children}
        </div>
      </body>
    </html>

  );
}
